title: Raffles Girls PeRL
url: https://rgs.perl.edu.sg
favicon: /images/logo.jpg
colors:
  primary-color: "#396805"
  secondary-color: "#396805"
  media-colors:
    - title: media-color-one
      color: "#396805"
    - title: media-color-two
      color: "#396805"
    - title: media-color-three
      color: "#396805"
    - title: media-color-four
      color: "#396805"
    - title: media-color-five
      color: "#396805"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dfkurcec4b4z0.amplifyapp.com
prod: https://master.dfkurcec4b4z0.amplifyapp.com
shareicon: /images/logo.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: achievement
